keypoints:
- "Nose"
# "neck",
- "Rshoulder"
- "Relbow"
- "Rwrist"
- "Lshoulder"
- "Lelbow"
- "Lwrist"
- "Rhip"
- "Rknee"
- "Rankle"
- "Lhip"
- "Lknee"
- "Lankle"
- "Reye"
- "Leye"
- "Rear"
- "Lear"

right_keypoints_indexes:
- 1
- 2
- 3
- 7
- 8
- 9
- 13
- 15

left_keypoints_indexes:
- 4
- 5
- 6
- 10
- 11
- 12
- 14
- 16